import type { Metadata } from "next";
import Header from "./Composant/Include/header";
import Footer from "./Composant/Include/footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./Style/globals.css";
import { Rubik } from 'next/font/google'

const rubik = Rubik({
  weight: '500',
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en" className={rubik.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// LA POLICE D'ÉCRITURE NE MARCHE PAS ENCORE
