import type { Metadata } from "next";
import Header from "./Composant/Include/header";
import Card from "./Composant/CardCategorie/CardCategorie";
import Footer from "./Composant/Include/footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./Style/globals.css";
import "./Style/style.css";

export const metadata: Metadata = {
  title: "MindNest",
  description: "Generated by create next app",
};

export default function RootLayout({children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* <Card titreCategorie={"Productivité / Élégance"}/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}